import {Dimensions, StyleSheet} from 'react-native';
import colors from '@constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    position: 'absolute',
    bottom: 60,
  },
  textInput: {
    margin: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.gray,
    backgroundColor: colors.white01,
    borderRadius: 25,
    height: 50,
    width: '90%',
    color: colors.white,
  },
  labelView: {
    position: 'absolute',
    height: '100%',
    width: 150,
    borderColor: colors.black,
    borderWidth: 2,
    borderRadius: 25,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  buttonLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    zIndex: 1,
    color: colors.black,
  },
  welcomeLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: Dimensions.get('screen').height / 2 - 150,
  },
  loginButton: {
    padding: 6,
    paddingHorizontal: 12,
    borderRadius: 25,
    height: 50,
    zIndex: 0,
    backgroundColor: colors.white,
    opacity: 0.3,
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundImage: {flex: 1},
  logo: {height: 150},
});
